### ISSUE TITLE
Configuration in working-dir is empty

### ISSUE THREAD

**Issue by vmichals** [Epistimio/orion#394] opened 2020-05-24 23:42 UTC
**Describe the bug**
I specified a working-dir to orion hunt and it creates subfolders for the trials, each with two files `results_*.log` and `trial_*.conf`. 
After a trial is completed the corresponding results file contains the result, but the configuration file remains empty.

**Expected behavior**
The configuration file should contain the trial's hyperparameter configuration.

**Steps to reproduce**
Call `orion hunt` with the `--working-dir` argument.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: e.g. 3.6.9
 - Oríon version: develop
 - Database: PickleDB

**Comment by Thomsch** [comment] 2020-05-25 14:25
Thanks for opening this issue! We'll fix this ASAP.

**Comment by bouthilx** [comment] 2020-06-16 16:45
![](https://github.trello.services/images/mini-trello-icon.png) [Configuration in working-dir is empty](https://trello.com/c/vuNerTEl/565-configuration-in-working-dir-is-empty)

**Comment by bouthilx** [comment] 2020-06-17 15:34
Hi Vincent, I'm trying to reproduce this issue without success so far. Could you please share your script configuration?

**Comment by Thomsch** [comment] 2020-06-23 19:00
> Hi Vincent, I'm trying to reproduce this issue without success so far. Could you please share your script configuration?

@vmichals

**Comment by vmichals** [comment] 2020-06-23 21:46
Hey, sorry I missed the notification! I believe it was this configuration:
``` 
experiment:
    algorithms: 
        asha:
            seed: null
            num_rungs: null
            num_brackets: 4
    strategy: StubParallelStrategy
```

**Comment by bouthilx** [comment] 2020-06-25 13:38
No worries, could you please share the commandline call and configuration file for your script as well.

**Comment by bouthilx** [comment] 2020-08-24 17:18
Hi @vmichals , do you still have the issue with latest develop version? I would close this issue otherwise. Thanks!

**Comment by bouthilx** [comment] 2020-09-22 17:25
I will close the issue since there is no update. Feel free to open it back if you still have the issue.

**Closed by bouthilx** 2020-09-22 17:25 UTC
Labels: bug, high
