### ISSUE TITLE
Sample-space bug in Oríon version: 0.2.7

### ISSUE THREAD

**Issue by Entodi** [Epistimio/orion#1100] opened 2023-06-09 13:54 UTC
**Describe the bug**
I have tried to run BOHB (https://orion.readthedocs.io/en/latest/code/algo/bohb.html), however it gives the error for sample-space package (sspace).

This is my error.
```bash
[2023-06-09 13:40:35,806][HYDRA] with parametrization {'bs': 'uniform(2, 256, discrete=True)', 'epoch': 'fidelity(5, 500)', 'lr': 'loguniform(1e-06, 0.01, precision=2)', 'wd': 'loguniform(1e-06, 0.01, precision=2)'}
[2023-06-09 13:40:37,021][HYDRA] algorithms is deprecated and will be removed in v0.4.0. Use algorithm instead.
Traceback (most recent call last):
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/orion/algo/bohb/bohb.py", line 20, in <module>
    from sspace.convert import convert_space, reverse, transform
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/sspace/__init__.py", line 11, in <module>
    from .space import Space
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/sspace/space.py", line 7, in <module>
    from space.orion.utils import flatten
ModuleNotFoundError: No module named 'space'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/hydra_plugins/hydra_orion_sweeper/orion_sweeper.py", line 79, in sweep
    return self.sweeper.sweep(arguments)
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/hydra_plugins/hydra_orion_sweeper/implementation.py", line 503, in sweep
    self.client = self.new_experiment(arguments)
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/hydra_plugins/hydra_orion_sweeper/implementation.py", line 478, in new_experiment
    return create_experiment(
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/orion/client/__init__.py", line 50, in create_experiment
    return build_experiment(name, **config)
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/orion/client/__init__.py", line 220, in build_experiment
    experiment = builder.build(
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/orion/core/io/experiment_builder.py", line 590, in build
    experiment = self.create_experiment(mode="x", **copy.deepcopy(config))
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/orion/core/io/experiment_builder.py", line 944, in create_experiment
    instantiated_algorithm = _instantiate_algo(
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/orion/core/io/experiment_builder.py", line 278, in _instantiate_algo
    wrapped_algo = create_algo(
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/orion/core/worker/primary_algo.py", line 106, in create_algo
    algorithm = algo_type(spaces.pop(), *algo_args, **algo_kwargs)
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/orion/algo/bohb/bohb.py", line 114, in __init__
    import_optional.ensure()
  File "<my_dor>anaconda3/envs/<my_env>/lib/python3.8/site-packages/orion/core/utils/module_import.py", line 82, in ensure
    raise ImportError(
ImportError: The package `BOHB` is not installed. Install it with `pip install orion[bohb]`.
```

**Expected behavior**
It gives the error that  `BOHB` is not installed, but the error should be given for sspace. Because import in sspace failed.

**Steps to reproduce**

0. Install `pip install orion[bohb]`
1. Clone https://github.com/Epistimio/hydra_orion_sweeper/tree/master/example
2. Add BOHB configuration to yaml instead on `random` strategy.
```yaml
  algorithm:
      type: bohb
      config:
        min_points_in_model: 20
        top_n_percent: 15
        num_samples: 100
        random_fraction: 0.33
        bandwidth_factor: 3
        parallel_strategy:
          of_type: StatusBasedParallelStrategy
          strategy_configs:
            broken:
                of_type: MaxParallelStrategy
```
3. Run the example with `python main.py --multirun`

**Environment (please complete the following information):**
 - OS: Ubuntu, 20.04.1
 - Python version: 3.8
 - Oríon version: 0.2.7
 - Orion-hydra-sweeper version: 1.6.3
 - Database: PickleDB

**Additional context**

**Possible solution**
You can fix it by installing a sample space from Git Hub as a temporary solution.
`pip install git+https://github.com/Epistimio/sample-space.git`

**Comment by mariam-jamal** [comment] 2023-06-10 11:05
I am facing a similar issue.. even after pip install orion[bohb], it gives an import error.
ImportError: The package `BOHB` is not installed. Install it with `pip install orion[bohb]`.

**Comment by Entodi** [comment] 2023-06-10 16:51
@mariam-jamal you can fix it by installing a sample space from Git Hub as a temporary solution.
`pip install git+https://github.com/Epistimio/sample-space.git`

**Comment by bouthilx** [comment] 2023-07-03 18:21
Hi, sorry for the long delay!

Did you notice when installing with `pip install orion[bohb]` if there was an error message about sample-space? The optional dependency `orion[bohb]` contains `"sspace @ git+https://github.com/Epistimio/sample-space.git@master#egg=sspace"` so I am a bit confused about why it would not have been installed.

**Comment by FrancoisPgm** [comment] 2024-02-06 21:07
Hi, I have a similar issue, with `pip install orion[bohb]` I get an import error caused by 
```
  File "/Users/fpaugam/scratch/test_orion/env/lib/python3.10/site-packages/sspace/space.py", line 7, in <module>
    from sspace.orion.utils import flatten
ModuleNotFoundError: No module named 'sspace.orion'
```
I think it would be fixed by [the unmerged PR on https://github.com/Epistimio/sample-space/](https://github.com/Epistimio/sample-space/pull/10)

So for me the fix from @Entodi doesn't work but with the `hotfix/missing-package` branch it does :
`pip install git+https://github.com/Epistimio/sample-space.git@hotfix/missing-package`

**Comment by bouthilx** [comment] 2024-02-13 18:04
Thanks for sharing! The PR is now merged and released. I'll close this issue assuming it's now solved. Please reopen if you still face similar issues with BOHB installation.

**Closed as completed by bouthilx** 2024-02-13 18:04 UTC
Labels: bug
