### ISSUE TITLE
Scipy fails to report the correct interval in integer distributions

### ISSUE THREAD

**Issue by tsirif** [Epistimio/orion#49] opened 2018-03-07 01:23 UTC
This [test](https://github.com/tsirif/metaopt/blob/feature/algorithm/tests/unittests/algo/test_space.py#L223) fails. `scipy.stats.distributions` seems not to have the needed implementation to support returning the correct interval (lower and upper bound) of integer distributions like `randint` or `poisson`.

For example:
```p
>>> from scipy.stats import distributions as dists
>>> dists.poisson.interval(alpha=1.0, mu=1.0)
(-1.0, inf)
```
, while it should return:
```p
(0.0, inf)
```

The problem is even more complex, if you add a displacement (through `loc` argument) or a scale (through `scale` argument) to the distribution.

**Comment by bouthilx** [comment] 2018-03-07 02:42
`poisson` we could survive for some time without it, but `randint` is quite annoying. Any idea what's the cause of this in `scipy.stats.distributions`?

**Comment by tsirif** [comment] 2018-03-08 21:37
So `interval` is calculated the same way for continuous and discrete distributions. The method resides in base class for all distribution generator classes: [`interval`](https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L127)
I haven't checked out thoroughly, but my initial guess is that the [`ppf`](https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L3043) method in `class rv_discrete(rv_generic)` is not implemented correctly :/

**Comment by bouthilx** [comment] 2018-03-14 15:51
Not implemented correctly? How so? Did you fine any issue opened about that? You should do so otherwise.

**Comment by tsirif** [comment] 2018-03-14 19:07
I can find out what's weird in particular. Would you suggest to take a look into it right now? I haven't reported it yet. I will open an issue with a suggestion and a test.

**Comment by bouthilx** [comment] 2018-03-14 19:09
I don't have time right now unfortunately. Tomorrow after the meeting maybe?

**Comment by tsirif** [comment] 2018-03-14 19:10
I mean to do it myself, right now. :stuck_out_tongue:

**Comment by bouthilx** [comment] 2018-03-14 19:13
Oh, my bad. I though your meant looking at it together. You please take a
look at it if you can. randint is important to support.

**Comment by bouthilx** [comment] 2019-02-07 14:48
@tsirif This was not fixed right?

**Comment by bouthilx** [comment] 2019-02-14 16:42
A user reported that `randint(2, *)` and `randint(0, *)` would sometimes return `1` and `-1` respectively. This is likely related to this issue. The scipy version was 1.2.0.

**Comment by bouthilx** [comment] 2020-03-31 14:52
I will close this issue since we invite users to use `any(discrete=True)` for discrete distributions, and now use uses `poisson`. :)

**Closed by bouthilx** 2020-03-31 14:52 UTC
