### ISSUE TITLE
Lots of repeated deprecation warnings when running benchmark 

### ISSUE THREAD

**Issue by lebrice** [Epistimio/orion#878] opened 2022-03-31 19:32 UTC
```python
from orion.benchmark.benchmark_client import get_or_create_benchmark
from orion.benchmark.assessment import AverageResult
from orion.benchmark.task import RosenBrock, EggHolder, CarromTable

benchmark = get_or_create_benchmark(name='benchmark',
    algorithms=['random', 'tpe'],
    targets=[
        {
            'assess': [AverageResult(3)],
            'task': [RosenBrock(25, dim=3), EggHolder(20, dim=4), CarromTable(20)]
        }
    ]
)
benchmark.process()
```

```console
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
(DEPRECATED) Option `worker.reservation_timeout` will be removed in v0.4. Use `worker.idle_timeout` instead.
```

**Comment by bouthilx** [comment] 2022-03-31 19:42
Yeah that's annoying. :( This issue is a duplicate of #862 so I'll close this one.

**Closed by bouthilx** 2022-03-31 19:42 UTC
Labels: bug
